[[main]]
name = "Services"
url = "/services/"
weight = 2

# [[main]]
# name = "Team"
# url = "/team/"
# weight = 2

[[main]]
name = "About Us"
url = "/about/"
weight = 3

[[main]]
name = "Contact"
url = "/contact/"
weight = 4

# Footer Menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About Us"
url = "/about/"
weight = 2

[[footer]]
name = "Services"
url = "/services/"
weight = 3

[[footer]]
name = "Contact"
url = "/contact/"
weight = 4
