[build]
    command = "hugo --gc --minify"
    publish = "public"

[context.production.environment]
    HUGO_VERSION = "1.126.1"
    HUGO_GOOGLE_ANALYTICS_ID = "G-VLW2VPS7H5"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.126.1"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.126.1"
